### ISSUE TITLE
Docker dev container doesn't start

### ISSUE THREAD

**Issue by pedrolamas** [mainsail-crew/mainsail#567]
**Describe the bug:**\

When I do `docker compose up -d` to start the Docker stack, I get a Nodejs error from inside the Docker container.

I've tested only on Windows, but given the error I would expect it to be happening on Linux/Mac systems also.

**Expected behavior:**\

To build the Docker image and run the container without issues.

**Logfiles:**\

Log from inside the npm container (with `docker logs <container>`:

```
> mainsail@2.1.0-rc1 serve
> vue-cli-service serve

 INFO  Starting development server...
Starting type checking service...
Using 1 worker with 2048MB memory limit
<s> [webpack.Progress] 0% compiling
<s> [webpack.Progress] 10% building 0/0 modules 0 active
<s> [webpack.Progress] 10% building 0/1 modules 1 active multi /home/node/mainsail/node_modules/webpack-dev-server/client/index.js /home/node/mainsail/node_modules/webpack/hot/dev-server.js ./src/main.ts
<s> [webpack.Progress] 10% building 1/1 modules 0 active
<s> [webpack.Progress] 10% building 1/1 modules 0 active
<s> [webpack.Progress] 10% building 1/2 modules 1 active multi /home/node/mainsail/node_modules/webpack/hot/dev-server.js /home/node/mainsail/node_modules/webpack-dev-server/client/index.js ./src/main.ts
<s> [webpack.Progress] 10% building 2/2 modules 0 active
<s> [webpack.Progress] 10% building 2/3 modules 1 active /home/node/mainsail/node_modules/webpack-dev-server/client/index.js
<s> [webpack.Progress] 10% building 2/4 modules 2 active /home/node/mainsail/node_modules/webpack/hot/dev-server.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/node/mainsail/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/node/mainsail/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/node/mainsail/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/node/mainsail/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/node/mainsail/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/node/mainsail/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/node/mainsail/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/node/mainsail/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/node/mainsail/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/node/mainsail/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/node/mainsail/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/node/mainsail/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/node/mainsail/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/node/mainsail/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
<s> [webpack.Progress] 10% building 2/5 modules 3 active /home/node/mainsail/node_modules/cache-loader/dist/cjs.js??ref--15-0!/home/node/mainsail/node_modules/babel-loader/lib/index.js!/home/node/mainsail/node_modules/ts-loader/index.js??ref--15-2!/home/node/mainsail/node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js??ref--14-0!/home/node/mainsail/src/main.ts
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/node/mainsail/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/node/mainsail/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/node/mainsail/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/node/mainsail/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/node/mainsail/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/node/mainsail/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/node/mainsail/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/node/mainsail/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/node/mainsail/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/node/mainsail/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/node/mainsail/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.4.0
npm notice
npm notice New patch version of npm available! 8.3.1 -> 8.3.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.3.2>
npm notice Run `npm install -g npm@8.3.2` to update!
npm notice
```

**Comment by meteyou** [comment]
thx for the report! i searched all packages and found the "guilty" package. this error is caused by webpack4 with node 17. in webpack 5 this problem was fixed, but unfortunately webpack 5 and vue-cli are not compatible...
