### ISSUE TITLE
Rpi3 bullseye update gpio problem

### ISSUE THREAD

**Issue by kawapiki** [mainsail-crew/mainsail#720]
### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Linux

### What happened?

I've just distroswitched my pi to bullseye with fw/kernel update, and everything goin well, but moonraker seems can not connect to klippers (pi, printer).

### What did you expect to happen instead?

Everythig  run as before just with new 

### How to reproduce this bug?

Update to Bullseye from Buster

### Additional information:

GPIOD version: 1.6.2-1+rpi1
Moonraker gives this:
`An error was detected while loading the moonraker components. Please check the logfile and fix the issue.

Following plugin has an error:

gpio
Failed to load power device [power printer] Section [power printer], option 'pin', GPIO Component not available

Failed to load power device [power spider_reset] Section [power spider_reset], option 'pin', GPIO Component not available

Failed to load button [button my_button] Unable to load component: (gpio)

Unparsed config option 'pin: gpiochip0/gpio17' detected in section [power printer]. This may be an option no longer available or could be the result of a module that failed to load. In the future this will result in a startup error.

Unparsed config option 'pin: gpiochip0/gpio4' detected in section [power spider_reset]. This may be an option no longer available or could be the result of a module that failed to load. In the future this will result in a startup error.

Unparsed config option 'pin: ^gpiochip0/gpio27' detected in section [button my_button]. This may be an option no longer available or could be the result of a module that failed to load. In the future this will result in a startup error.`

moonraker.conf useful:
`[power printer]
type: gpio
pin: gpiochip0/gpio17
off_when_shutdown: True
restart_klipper_when_powered: true
initial_state: off

[power spider_reset]
type: gpio
pin: gpiochip0/gpio4
initial_state: off
timer: 1

[button my_button]
type: gpio
pin: ^gpiochip0/gpio27`

moonraker.log:
`Trusted Clients:
10.0.0.0/8
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.0.0/16
fe80::/10
::1/128
CORS Domains:
https://my\.mainsail\.xyz
http://my\.mainsail\.xyz
http://.*\.local
http://.*\.lan
2022-03-15 22:02:09,705 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /access/login
2022-03-15 22:02:09,705 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /access/logout
2022-03-15 22:02:09,706 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /access/refresh_jwt
2022-03-15 22:02:09,707 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET POST DELETE) /access/user
2022-03-15 22:02:09,707 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /access/users/list
2022-03-15 22:02:09,708 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /access/user/password
2022-03-15 22:02:09,709 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET POST) /access/api_key
2022-03-15 22:02:09,709 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /access/oneshot_token
2022-03-15 22:02:09,710 [moonraker.py:load_component()] - Component (authorization) loaded
2022-03-15 22:02:09,714 [power.py:__init__()] - Power component loading devices: ['power printer', 'power spider_reset']
2022-03-15 22:02:09,721 [moonraker.py:load_component()] - Unable to load component: (gpio)
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/moonraker.py", line 237, in load_component
    component = load_func(config)
  File "/home/pi/moonraker/moonraker/components/gpio.py", line 280, in load_component
    return GpioFactory(config)
  File "/home/pi/moonraker/moonraker/components/gpio.py", line 28, in __init__
    self.gpiod: Any = load_system_module("gpiod")
  File "/home/pi/moonraker/moonraker/utils.py", line 231, in load_system_module
    raise ServerError(f"Unable to import module {name}")
utils.ServerError: Unable to import module gpiod
2022-03-15 22:02:09,721 [moonraker.py:add_warning()] - Failed to load power device [power printer]
Section [power printer], option 'pin', GPIO Component not available
2022-03-15 22:02:09,724 [moonraker.py:load_component()] - Unable to load component: (gpio)
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/moonraker.py", line 237, in load_component
    component = load_func(config)
  File "/home/pi/moonraker/moonraker/components/gpio.py", line 280, in load_component
    return GpioFactory(config)
  File "/home/pi/moonraker/moonraker/components/gpio.py", line 28, in __init__
    self.gpiod: Any = load_system_module("gpiod")
  File "/home/pi/moonraker/moonraker/utils.py", line 231, in load_system_module
    raise ServerError(f"Unable to import module {name}")
utils.ServerError: Unable to import module gpiod
2022-03-15 22:02:09,724 [moonraker.py:add_warning()] - Failed to load power device [power spider_reset]
Section [power spider_reset], option 'pin', GPIO Component not available
2022-03-15 22:02:09,725 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /machine/device_power/devices
2022-03-15 22:02:09,726 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.device_power.devices
2022-03-15 22:02:09,726 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /machine/device_power/status
2022-03-15 22:02:09,727 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.device_power.status
2022-03-15 22:02:09,727 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/device_power/on
2022-03-15 22:02:09,727 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.device_power.on
2022-03-15 22:02:09,728 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/device_power/off
2022-03-15 22:02:09,728 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.device_power.off
2022-03-15 22:02:09,728 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET POST) /machine/device_power/device
2022-03-15 22:02:09,730 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.device_power.get_device, machine.device_power.post_device
2022-03-15 22:02:09,730 [moonraker.py:load_component()] - Component (power) loaded
2022-03-15 22:02:09,732 [button.py:__init__()] - Loading Buttons: ['button my_button']
2022-03-15 22:02:09,735 [moonraker.py:load_component()] - Unable to load component: (gpio)
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/moonraker.py", line 237, in load_component
    component = load_func(config)
  File "/home/pi/moonraker/moonraker/components/gpio.py", line 280, in load_component
    return GpioFactory(config)
  File "/home/pi/moonraker/moonraker/components/gpio.py", line 28, in __init__
    self.gpiod: Any = load_system_module("gpiod")
  File "/home/pi/moonraker/moonraker/utils.py", line 231, in load_system_module
    raise ServerError(f"Unable to import module {name}")
utils.ServerError: Unable to import module gpiod
2022-03-15 22:02:09,735 [moonraker.py:add_warning()] - Failed to load button [button my_button]
Unable to load component: (gpio)
2022-03-15 22:02:09,735 [moonraker.py:load_component()] - Component (button) loaded
2022-03-15 22:02:09,738 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /api/version
2022-03-15 22:02:09,738 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /api/server
2022-03-15 22:02:09,739 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /api/login
2022-03-15 22:02:09,739 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /api/currentuser
2022-03-15 22:02:09,740 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /api/settings
2022-03-15 22:02:09,740 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /api/job
2022-03-15 22:02:09,741 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /api/printer
2022-03-15 22:02:09,742 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /api/printer/command
2022-03-15 22:02:09,742 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /api/printerprofiles
2022-03-15 22:02:09,744 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /api/files/moonraker/(?P<relative_path>.+)
2022-03-15 22:02:09,745 [moonraker.py:load_component()] - Component (octoprint_compat) loaded
2022-03-15 22:02:09,747 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET DELETE) /server/history/job
2022-03-15 22:02:09,748 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.history.get_job, server.history.delete_job
2022-03-15 22:02:09,748 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /server/history/list
2022-03-15 22:02:09,749 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.history.list
2022-03-15 22:02:09,749 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /server/history/totals
2022-03-15 22:02:09,749 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.history.totals
2022-03-15 22:02:09,750 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /server/history/reset_totals
2022-03-15 22:02:09,750 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: server.history.reset_totals
2022-03-15 22:02:09,751 [moonraker.py:load_component()] - Component (history) loaded
2022-03-15 22:02:09,890 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/moonraker
2022-03-15 22:02:09,891 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.moonraker
2022-03-15 22:02:09,892 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/klipper
2022-03-15 22:02:09,892 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.klipper
2022-03-15 22:02:09,892 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/system
2022-03-15 22:02:09,893 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.system
2022-03-15 22:02:09,893 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/client
2022-03-15 22:02:09,894 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.client
2022-03-15 22:02:09,894 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/full
2022-03-15 22:02:09,895 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.full
2022-03-15 22:02:09,895 [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /machine/update/status
2022-03-15 22:02:09,896 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.status
2022-03-15 22:02:09,896 [app.py:register_local_handler()] - Registering HTTP Endpoint: (POST) /machine/update/recover
2022-03-15 22:02:09,897 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: machine.update.recover
2022-03-15 22:02:09,897 [moonraker.py:load_component()] - Component (update_manager) loaded
2022-03-15 22:02:09,897 [moonraker.py:add_warning()] - Unparsed config option 'pin: gpiochip0/gpio17' detected in section [power printer].  This may be an option no longer available or could be the result of a module that failed to load.  In the future this will result in a startup error.
2022-03-15 22:02:09,897 [moonraker.py:add_warning()] - Unparsed config option 'pin: gpiochip0/gpio4' detected in section [power spider_reset].  This may be an option no longer available or could be the result of a module that failed to load.  In the future this will result in a startup error.
2022-03-15 22:02:09,898 [moonraker.py:add_warning()] - Unparsed config option 'pin: ^gpiochip0/gpio27' detected in section [button my_button].  This may be an option no longer available or could be the result of a module that failed to load.  In the future this will result in a startup error.
2022-03-15 22:02:09,898 [moonraker.py:_initialize_component()] - Performing Component Post Init: [dbus_manager]
2022-03-15 22:02:09,924 [moonraker.py:_initialize_component()] - Performing Component Post Init: [file_manager]
2022-03-15 22:02:09,925 [moonraker.py:_initialize_component()] - Performing Component Post Init: [machine]
2022-03-15 22:02:10,189 [machine.py:check_virt_status()] - No Virtualization Detected
2022-03-15 22:02:10,205 [moonraker.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2022-03-15 22:02:10,206 [moonraker.py:_initialize_component()] - Performing Component Post Init: [authorization]
2022-03-15 22:02:10,206 [moonraker.py:_initialize_component()] - Performing Component Post Init: [power]
2022-03-15 22:02:10,206 [moonraker.py:_initialize_component()] - Performing Component Post Init: [button]
2022-03-15 22:02:10,207 [moonraker.py:_initialize_component()] - Performing Component Post Init: [update_manager]
2022-03-15 22:02:10,272 [update_manager.py:initialize()] - PackageDeploy: Using PackageKit Provider
2022-03-15 22:02:10,273 [update_manager.py:initialize()] - 
Initializing Client Updater: 'mainsail',
Channel: stable
path: /home/pi/mainsail
2022-03-15 22:02:10,274 [moonraker.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: voron
2022-03-15 22:02:10,277 [app.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2022-03-15 22:02:10,490 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.92
2022-03-15 22:02:10,493 [app.py:log_request()] - 101 GET /websocket (192.168.1.92) [_TRUSTED_USER_] 4.29ms
2022-03-15 22:02:10,493 [websockets.py:open()] - Websocket Opened: ID: 1739068816, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36, Host Name: 192.168.1.40
2022-03-15 22:02:10,530 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2022-03-15 22:02:10,784 [klippy_connection.py:_init_klippy_connection()] - Webhooks Subscribed
2022-03-15 22:02:10,787 [klippy_connection.py:_init_klippy_connection()] - GCode Output Subscribed
2022-03-15 22:02:10,801 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/info
2022-03-15 22:02:10,802 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.info
2022-03-15 22:02:10,802 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/query_endstops/status
2022-03-15 22:02:10,803 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.query_endstops.status
2022-03-15 22:02:10,803 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/emergency_stop
2022-03-15 22:02:10,804 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.emergency_stop
2022-03-15 22:02:10,804 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/pause_resume/pause
2022-03-15 22:02:10,805 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.pause_resume.pause
2022-03-15 22:02:10,805 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/objects/query
2022-03-15 22:02:10,805 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.objects.query
2022-03-15 22:02:10,805 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/objects/list
2022-03-15 22:02:10,806 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.objects.list
2022-03-15 22:02:10,807 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/motion_report/dump_stepper
2022-03-15 22:02:10,808 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.motion_report.dump_stepper
2022-03-15 22:02:10,808 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/gcode/firmware_restart
2022-03-15 22:02:10,809 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.gcode.firmware_restart
2022-03-15 22:02:10,809 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/objects/subscribe
2022-03-15 22:02:10,810 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.objects.subscribe
2022-03-15 22:02:10,810 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/gcode/script
2022-03-15 22:02:10,810 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.gcode.script
2022-03-15 22:02:10,811 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/gcode/help
2022-03-15 22:02:10,811 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.gcode.help
2022-03-15 22:02:10,811 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/pause_resume/resume
2022-03-15 22:02:10,812 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.pause_resume.resume
2022-03-15 22:02:10,813 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/pause_resume/cancel
2022-03-15 22:02:10,814 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.pause_resume.cancel
2022-03-15 22:02:10,814 [app.py:register_remote_handler()] - Registering HTTP endpoint: (GET POST) /printer/gcode/restart
2022-03-15 22:02:10,814 [websockets.py:register_api_handler()] - Registering Websocket JSON-RPC methods: printer.gcode.restart
2022-03-15 22:02:10,815 [klippy_connection.py:_check_ready()] - 
mcu 'mcu': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

2022-03-15 22:02:13,719 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2022-03-15 22:02:14,983 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2022-03-15 22:02:16,211 [klippy_connection.py:_init_klippy_connection()] - Webhooks Subscribed
2022-03-15 22:02:16,231 [klippy_connection.py:_init_klippy_connection()] - GCode Output Subscribed
2022-03-15 22:02:49,614 [websockets.py:build_error()] - JSON-RPC Request Error: -31000
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/websockets.py", line 225, in execute_method
    result = await method(conn, *args, **kwargs)
  File "/home/pi/moonraker/moonraker/websockets.py", line 333, in func
    ip_addr=ws.ip_addr, user=ws.current_user))
  File "/home/pi/moonraker/moonraker/components/klippy_apis.py", line 78, in _gcode_restart
    return await self.do_restart("RESTART")
  File "/home/pi/moonraker/moonraker/components/klippy_apis.py", line 127, in do_restart
    await self.klippy.wait_started()
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 108, in wait_started
    asyncio.shield(self.connection_task), timeout=timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
2022-03-15 22:03:49,082 [klippy_connection.py:_check_ready()] - 
mcu 'mcu': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer
`

**Comment by th33xitus** [comment]
![image](https://user-images.githubusercontent.com/31533186/158473727-c3da9192-9b6f-4c69-ac9b-cd57f30f14fb.png)

This bug report is invalid.
If you need help/assistance with Moonraker related problems, please use Discord.
